/**
 * Alert Routes — Email notification for critical offenses
 * Uses Gmail SMTP via Nodemailer to alert users.
 */

const express    = require('express');
const nodemailer = require('nodemailer');
const router     = express.Router();

/* ── Gmail SMTP transporter (lazy-init) ── */
let transporter = null;

function getTransporter() {
  if (!transporter) {
    const gmailUser = process.env.GMAIL_USER;
    const gmailPass = process.env.GMAIL_APP_PASSWORD;

    if (!gmailUser || !gmailPass) {
      console.warn('⚠ GMAIL_USER / GMAIL_APP_PASSWORD not set — email alerts disabled');
      return null;
    }

    transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: gmailUser,
        pass: gmailPass,
      },
    });
  }
  return transporter;
}

/* ── Build HTML email for critical alert ── */
function buildAlertEmail(alertData) {
  const { offenseName, severity, source, count, timestamp, details } = alertData;

  const severityColor = severity === 'critical' ? '#ef4444'
                      : severity === 'high'     ? '#f97316'
                      : '#eab308';

  return `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; background: #0f1117; color: #e5e7eb; margin: 0; padding: 0; }
    .container { max-width: 600px; margin: 0 auto; padding: 32px 24px; }
    .header { display: flex; align-items: center; gap: 12px; margin-bottom: 24px; }
    .logo { font-size: 22px; font-weight: 700; color: #3b82f6; }
    .alert-banner { background: ${severityColor}15; border: 1px solid ${severityColor}55; border-left: 4px solid ${severityColor}; border-radius: 8px; padding: 20px; margin-bottom: 20px; }
    .alert-title { font-size: 18px; font-weight: 700; color: ${severityColor}; margin: 0 0 8px 0; }
    .alert-subtitle { font-size: 14px; color: #9ca3af; margin: 0; }
    .details-table { width: 100%; border-collapse: collapse; margin: 16px 0; }
    .details-table td { padding: 10px 14px; border-bottom: 1px solid #1f2937; font-size: 14px; }
    .details-table td:first-child { color: #9ca3af; font-weight: 500; width: 130px; }
    .details-table td:last-child { color: #e5e7eb; }
    .badge { display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 11px; font-weight: 700; text-transform: uppercase; background: ${severityColor}25; color: ${severityColor}; }
    .footer { margin-top: 24px; padding-top: 16px; border-top: 1px solid #1f2937; font-size: 12px; color: #6b7280; }
    .action-btn { display: inline-block; padding: 10px 24px; background: #3b82f6; color: white; text-decoration: none; border-radius: 6px; font-weight: 600; font-size: 14px; margin-top: 16px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <span class="logo">WazuhBot</span>
      <span style="color: #6b7280;">Security Alert</span>
    </div>

    <div class="alert-banner">
      <p class="alert-title">${offenseName}</p>
      <p class="alert-subtitle">A ${severity} severity security event has been detected.</p>
    </div>

    <table class="details-table">
      <tr><td>Severity</td><td><span class="badge">${severity.toUpperCase()}</span></td></tr>
      <tr><td>Source</td><td>${source || 'Unknown'}</td></tr>
      <tr><td>Event Count</td><td>${count || 'N/A'}</td></tr>
      <tr><td>Detected At</td><td>${timestamp || new Date().toISOString()}</td></tr>
      ${details ? `<tr><td>Details</td><td>${details}</td></tr>` : ''}
    </table>

    <p style="font-size: 14px; color: #d1d5db;">
      <strong>Recommended Action:</strong> Log in to WazuhBot to investigate this alert and take appropriate remediation steps.
    </p>

    <div class="footer">
      <p>This alert was generated by WazuhBot Sentinel. You can manage alert preferences in Settings.</p>
      <p>If you did not expect this email, please contact your administrator.</p>
    </div>
  </div>
</body>
</html>`;
}

/* ── POST /api/alerts/send — Send alert email ── */
router.post('/send', async (req, res) => {
  const { email, alertData } = req.body;

  if (!email || !alertData) {
    return res.status(400).json({ error: 'email and alertData are required' });
  }

  const transport = getTransporter();
  if (!transport) {
    return res.status(503).json({
      error:  'Email service not configured',
      hint:   'Set GMAIL_USER and GMAIL_APP_PASSWORD in Backend/.env',
    });
  }

  try {
    const html = buildAlertEmail(alertData);

    await transport.sendMail({
      from:    `"WazuhBot Alert" <${process.env.GMAIL_USER}>`,
      to:      email,
      subject: `[${alertData.severity.toUpperCase()}] ${alertData.offenseName} — WazuhBot Alert`,
      html,
    });

    res.json({ success: true, message: `Alert email sent to ${email}` });
  } catch (err) {
    console.error('Email send error:', err.message);
    res.status(500).json({ error: 'Failed to send email', details: err.message });
  }
});

/* ── GET /api/alerts/test — Test email config ── */
router.get('/test', async (req, res) => {
  const transport = getTransporter();
  if (!transport) {
    return res.status(503).json({ configured: false, hint: 'Set GMAIL_USER and GMAIL_APP_PASSWORD' });
  }

  try {
    await transport.verify();
    res.json({ configured: true, message: 'Gmail SMTP connection verified' });
  } catch (err) {
    res.status(500).json({ configured: false, error: err.message });
  }
});

module.exports = router;
