require('dotenv').config();
const express = require('express');
const oracledb = require('oracledb');
const cors = require('cors');

const authRoutes = require('./routes/auth');

const app = express();
const PORT = process.env.PORT || 5000;

/* ── Middleware ── */
app.use(cors());
app.use(express.json());

/* ── Routes ── */
app.use('/api/auth', authRoutes);

/* ── Health check ── */
app.get('/api/health', (_req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

/* ── Initialize Oracle Connection Pool & start server ── */
async function startServer() {
  try {
    // Use Thin mode (no Oracle Client libraries needed)
    oracledb.initOracleClient && oracledb.initOracleClient();
  } catch (_) { /* thin mode, no client needed */ }

  try {
    await oracledb.createPool({
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      connectString: process.env.DB_CONNECTION_STRING,
      poolMin: 2,
      poolMax: 10,
      poolIncrement: 1,
    });
    console.log('✅ Oracle DB connection pool created');

    // Create USERS table if it does not exist
    const conn = await oracledb.getConnection();
    try {
      await conn.execute(`
        BEGIN
          EXECUTE IMMEDIATE '
            CREATE TABLE USERS (
              ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              FULL_NAME    VARCHAR2(100)  NOT NULL,
              EMAIL        VARCHAR2(255)  UNIQUE NOT NULL,
              PASSWORD_HASH VARCHAR2(255) NOT NULL,
              ORGANIZATION VARCHAR2(255)  DEFAULT '''''' ,
              WAZUH_IP     VARCHAR2(100)  DEFAULT '''''' ,
              CREATED_AT   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
            )
          ';
        EXCEPTION
          WHEN OTHERS THEN
            IF SQLCODE = -955 THEN NULL;
            ELSE RAISE;
            END IF;
        END;
      `);
      await conn.commit();
    } finally {
      await conn.close();
    }
    console.log('✅ USERS table ready');

    app.listen(PORT, () => {
      console.log(`🚀 Backend running on http://localhost:${PORT}`);
    });
  } catch (err) {
    console.error('❌ Oracle startup error:', err.message);
    process.exit(1);
  }
}

startServer();
